Pandas is a python library used for working with data sets, it is wide used in data analysis,data science and machine learning.
**series** is like a column in a table, it is a one-dimensional array holding data of any type.
**DataFrames**: A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [2]:
import pandas as pd
print(pd.__version__)  # to check version

2.3.3

In [9]:
import pandas as pd
data = [100,102,202]

series = pd.Series(data, index=["a","b","c"])
print(series)

a    100
b    102
c    202
dtype: int64

**Locate Row:** Pandas use loc attribute to return one or more specified rows.
**iloc** iloc property gets,or sets the values of a specified indexes.

In [10]:
import pandas as pd
data = [100,102,202]

series = pd.Series(data, index=["a","b","c"])
series.loc["c"] = 200
print(series)

a    100
b    102
c    200
dtype: int64

In [14]:
#iloc  = interger location
import pandas as pd

values = [58,85,69,96,22]
series = pd.Series(values, index=["a","b","c","d","e"])
print(series.iloc[0])
print(series[series > 50])

58
a    58
b    85
c    69
d    96
dtype: int64

In [18]:
import pandas as pd

calories = {"Day1" : 1750, "Day2" : 2100, "Day3" : 1700}
series = pd.Series(calories)

series.loc["Day3"] += 400
print(series)

Day1    1750
Day2    2100
Day3    2100
dtype: int64

In [ ]:
**DataFrames**: A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [31]:
import pandas as pd

data = {
    "Name" : ["Spongebob", "Patrick", "Squidward"],
    "Age" :[30,35,50]
}
df = pd.DataFrame(data, index = ["Employee 1", "Employee 2", "Employee 3"])

# Add a new Column
df["Job"] = ["Cook","N/A","Cashier"]

# Add a new row 

new_row = pd.DataFrame([{"Name":"Sandy","Age": 28,"Job": "Engineer"},
                       {"Name":"Eugene","Age": 60,"Job": "Manager"}],
                     index=["Employee 4","Employee 5"] )
df = pd.concat([df, new_row])
print(df)

                 Name  Age       Job
Employee 1  Spongebob   30      Cook
Employee 2    Patrick   35       N/A
Employee 3  Squidward   50   Cashier
Employee 4      Sandy   28  Engineer
Employee 5     Eugene   60   Manager

In [26]:
import pandas as pd

data = {
    "Name" : ["Spongebob", "Patrick", "Squidward"],
    "Age" :[30,35,50]
}
df = pd.DataFrame(data, index = ["Employee 1", "Employee 2", "Employee 3"])
print(df.loc["Employee 1"])
print(df.iloc[2])

Name    Spongebob
Age            30
Name: Employee 1, dtype: object
Name    Squidward
Age            50
Name: Employee 3, dtype: object

**Importing csv and json files**
**Comma-seperated files(CSV)**
A simple way to store big data sets is to use CSV files.

CSV files contains plain text and is a well know format that can be read by everyone including Pandas.

In [39]:
import pandas as pd
df = pd.read_csv("one_piece.csv")
print(df)

    ID                   Name            Role  Episode                  Arc
0    1        Monkey D. Luffy         Captain        1            East Blue
1    2           Roronoa Zoro       Swordsman        2            East Blue
2    3                   Nami       Navigator        1            East Blue
3    4                  Usopp          Sniper        9            East Blue
4    5                  Sanji            Cook       20              Baratie
5    6      Tony Tony Chopper          Doctor       81          Drum Island
6    7             Nico Robin   Archaeologist       67             Alabasta
7    8                 Franky      Shipwright      233              Water 7
8    9                  Brook        Musician      337        Thriller Bark
9   10                  Jinbe        Helmsman      430      Fish-Man Island
10  11         Portgas D. Ace          Pirate       91             Alabasta
11  12       Trafalgar D. Law         Captain      392              Sabaody
12  13            Eustass Kid         Captain      398              Sabaody
13  14                 Shanks         Emperor        4            East Blue
14  15      Marshall D. Teach         Emperor       96                 Jaya
15  16         Dracule Mihawk       Swordsman       23              Baratie
16  17        Buggy the Clown         Captain        4          Orange Town
17  18              Crocodile         Warlord       76             Alabasta
18  19  Donquixote Doflamingo         Warlord      151            Dressrosa
19  20            Boa Hancock         Empress      410          Amazon Lily
20  21                  Kaido         Emperor      739                 Wano
21  22                Big Mom         Emperor      571    Whole Cake Island
22  23         Edward Newgate         Emperor      151           Marineford
23  24               Sakazuki   Fleet Admiral      278           Marineford
24  25                  Kuzan         Admiral      227  Long Ring Long Land
25  26              Borsalino         Admiral      398              Sabaody
26  27         Monkey D. Garp    Vice Admiral       68              Water 7
27  28                Sengoku   Fleet Admiral      151           Marineford
28  29                 Smoker         Captain       48            Loguetown
29  30                Tashigi         Officer       48            Loguetown
30  31                   Enel             God      167              Skypiea
31  32              Rob Lucci        Assassin      229              Water 7
32  33                   Kaku        Assassin      229              Water 7
33  34                 Blueno        Assassin      229              Water 7
34  35            Gecko Moria         Warlord      343        Thriller Bark
35  36                 Perona          Pirate      343        Thriller Bark
36  37       Bartholomew Kuma         Warlord      151        Thriller Bark
37  38                   Sabo  Chief of Staff      663            Dressrosa
38  39       Monkey D. Dragon          Leader       52            Loguetown
39  40        Emporio Ivankov       Commander      438           Impel Down
40  41               Magellan          Warden      425           Impel Down
41  42              Hannyabal     Vice Warden      425           Impel Down
42  43                 Shiryu       Swordsman      440           Impel Down
43  44                   King       Commander      918                 Wano
44  45                  Queen       Commander      918                 Wano
45  46                   Jack       Commander      750                  Zou
46  47     Charlotte Katakuri       Commander      825    Whole Cake Island
47  48      Charlotte Cracker       Commander      800    Whole Cake Island
48  49                  Marco       Commander      151           Marineford
49  50                  Vista       Commander      151           Marineford

In [3]:
import pandas as pd
df = pd.read_csv("one_piece.csv")

#Selection by column
print(df[["Name","Role"]])

                     Name            Role
0         Monkey D. Luffy         Captain
1            Roronoa Zoro       Swordsman
2                    Nami       Navigator
3                   Usopp          Sniper
4                   Sanji            Cook
5       Tony Tony Chopper          Doctor
6              Nico Robin   Archaeologist
7                  Franky      Shipwright
8                   Brook        Musician
9                   Jinbe        Helmsman
10         Portgas D. Ace          Pirate
11       Trafalgar D. Law         Captain
12            Eustass Kid         Captain
13                 Shanks         Emperor
14      Marshall D. Teach         Emperor
15         Dracule Mihawk       Swordsman
16        Buggy the Clown         Captain
17              Crocodile         Warlord
18  Donquixote Doflamingo         Warlord
19            Boa Hancock         Empress
20                  Kaido         Emperor
21                Big Mom         Emperor
22         Edward Newgate         Emperor
23               Sakazuki   Fleet Admiral
24                  Kuzan         Admiral
25              Borsalino         Admiral
26         Monkey D. Garp    Vice Admiral
27                Sengoku   Fleet Admiral
28                 Smoker         Captain
29                Tashigi         Officer
30                   Enel             God
31              Rob Lucci        Assassin
32                   Kaku        Assassin
33                 Blueno        Assassin
34            Gecko Moria         Warlord
35                 Perona          Pirate
36       Bartholomew Kuma         Warlord
37                   Sabo  Chief of Staff
38       Monkey D. Dragon          Leader
39        Emporio Ivankov       Commander
40               Magellan          Warden
41              Hannyabal     Vice Warden
42                 Shiryu       Swordsman
43                   King       Commander
44                  Queen       Commander
45                   Jack       Commander
46     Charlotte Katakuri       Commander
47      Charlotte Cracker       Commander
48                  Marco       Commander
49                  Vista       Commander

In [11]:
import pandas as pd
df = pd.read_csv("one_piece.csv", index_col = "Name")

#Selection by rows
print(df.loc["Monkey D. Dragon"])

ID                39
Role          Leader
Episode           52
Arc        Loguetown
Name: Monkey D. Dragon, dtype: object

In [13]:
import pandas as pd
df = pd.read_csv("one_piece.csv", index_col = "Name")

#Selection by rows
print(df.loc["Monkey D. Luffy":"Jinbe", ["Role","Arc"]])  #use slice

                            Role              Arc
Name
Monkey D. Luffy          Captain        East Blue
Roronoa Zoro           Swordsman        East Blue
Nami                   Navigator        East Blue
Usopp                     Sniper        East Blue
Sanji                       Cook          Baratie
Tony Tony Chopper         Doctor      Drum Island
Nico Robin         Archaeologist         Alabasta
Franky                Shipwright          Water 7
Brook                   Musician    Thriller Bark
Jinbe                   Helmsman  Fish-Man Island

In [16]:
import pandas as pd
df = pd.read_csv("one_piece.csv")

print(df.iloc[0:15])

    ID               Name           Role  Episode              Arc
0    1    Monkey D. Luffy        Captain        1        East Blue
1    2       Roronoa Zoro      Swordsman        2        East Blue
2    3               Nami      Navigator        1        East Blue
3    4              Usopp         Sniper        9        East Blue
4    5              Sanji           Cook       20          Baratie
5    6  Tony Tony Chopper         Doctor       81      Drum Island
6    7         Nico Robin  Archaeologist       67         Alabasta
7    8             Franky     Shipwright      233          Water 7
8    9              Brook       Musician      337    Thriller Bark
9   10              Jinbe       Helmsman      430  Fish-Man Island
10  11     Portgas D. Ace         Pirate       91         Alabasta
11  12   Trafalgar D. Law        Captain      392          Sabaody
12  13        Eustass Kid        Captain      398          Sabaody
13  14             Shanks        Emperor        4        East Blue
14  15  Marshall D. Teach        Emperor       96             Jaya

In [18]:
import pandas as pd
df = pd.read_csv("one_piece.csv")

print(df.iloc[0:15:2, 0:3])  # printing every second row and also select columns

    ID               Name           Role
0    1    Monkey D. Luffy        Captain
2    3               Nami      Navigator
4    5              Sanji           Cook
6    7         Nico Robin  Archaeologist
8    9              Brook       Musician
10  11     Portgas D. Ace         Pirate
12  13        Eustass Kid        Captain
14  15  Marshall D. Teach        Emperor

In [4]:
#EXERCISE

import pandas as pd

df = pd.read_csv("one_piece.csv", index_col="Name")

one_piece = input("Enter a Character name: ")

try:
    print(df.loc[one_piece])
except KeyError:
    print(f"{one_piece} does not exist")

Enter a Character name:  Eustass Kid

ID              13
Role       Captain
Episode        398
Arc        Sabaody
Name: Eustass Kid, dtype: object

In [5]:
#Filtering = Keeping the rows that match a condition
import pandas as pd

df = pd.read_csv("one_piece.csv")

# Filter all Captains
captains = df[df["Role"] == "Captain"]
print(captains)

    ID              Name     Role  Episode          Arc
0    1   Monkey D. Luffy  Captain        1    East Blue
11  12  Trafalgar D. Law  Captain      392      Sabaody
12  13       Eustass Kid  Captain      398      Sabaody
16  17   Buggy the Clown  Captain        4  Orange Town
28  29            Smoker  Captain       48    Loguetown

In [6]:
import pandas as pd
df = pd.read_csv("one_piece.csv")

# Captain AND from East Blue arc and Multiple Conditions (AND)
result = df[(df["Role"] == "Captain") & (df["Arc"] == "East Blue")]
print(result)

   ID             Name     Role  Episode        Arc
0   1  Monkey D. Luffy  Captain        1  East Blue

In [7]:
import pandas as pd
df = pd.read_csv("one_piece.csv")

# Characters appearing after episode 500
#Filter by Episode (Numbers)
result = df[df["Episode"] > 500]
print(result)

    ID                Name            Role  Episode                Arc
20  21               Kaido         Emperor      739               Wano
21  22             Big Mom         Emperor      571  Whole Cake Island
37  38                Sabo  Chief of Staff      663          Dressrosa
43  44                King       Commander      918               Wano
44  45               Queen       Commander      918               Wano
45  46                Jack       Commander      750                Zou
46  47  Charlotte Katakuri       Commander      825  Whole Cake Island
47  48   Charlotte Cracker       Commander      800  Whole Cake Island

In [8]:
import pandas as pd
df = pd.read_csv("one_piece.csv")

# Characters from Wano OR Marineford
#Multiple Conditions (OR)
result = df[(df["Arc"] == "Wano") | (df["Arc"] == "Marineford")]
print(result)

    ID            Name           Role  Episode         Arc
20  21           Kaido        Emperor      739        Wano
22  23  Edward Newgate        Emperor      151  Marineford
23  24        Sakazuki  Fleet Admiral      278  Marineford
27  28         Sengoku  Fleet Admiral      151  Marineford
43  44            King      Commander      918        Wano
44  45           Queen      Commander      918        Wano
48  49           Marco      Commander      151  Marineford
49  50           Vista      Commander      151  Marineford

**Aggregation** in pandas is all about summarizing your data—turning many rows into meaningful insights like totals, averages, counts, etc.

In [9]:
import pandas as pd

df = pd.read_csv("one_piece.csv")

df["Episode"].mean()

np.float64(283.04)

In [10]:
import pandas as pd
df = pd.read_csv("one_piece.csv")

df["Episode"].max()

1

In [11]:
import pandas as pd
df = pd.read_csv("one_piece.csv")

df["Episode"].min()

1

In [12]:
import pandas as pd
df = pd.read_csv("one_piece.csv")

df["Name"].count()

np.int64(50)

In [13]:
#GroupBy + Aggregation
import pandas as pd
df = pd.read_csv("one_piece.csv")

#Count characters per Arc
df.groupby("Arc")["Name"].count()

Arc
Alabasta               3
Amazon Lily            1
Baratie                2
Dressrosa              2
Drum Island            1
East Blue              5
Fish-Man Island        1
Impel Down             4
Jaya                   1
Loguetown              3
Long Ring Long Land    1
Marineford             5
Orange Town            1
Sabaody                3
Skypiea                1
Thriller Bark          4
Wano                   3
Water 7                5
Whole Cake Island      3
Zou                    1
Name: Name, dtype: int64

In [14]:
import pandas as pd
df = pd.read_csv("one_piece.csv")

#Average Episode per Arc
df.groupby("Arc")["Episode"].mean()

Arc
Alabasta                78.000000
Amazon Lily            410.000000
Baratie                 21.500000
Dressrosa              407.000000
Drum Island             81.000000
East Blue                3.400000
Fish-Man Island        430.000000
Impel Down             432.000000
Jaya                    96.000000
Loguetown               49.333333
Long Ring Long Land    227.000000
Marineford             176.400000
Orange Town              4.000000
Sabaody                396.000000
Skypiea                167.000000
Thriller Bark          293.500000
Wano                   858.333333
Water 7                197.600000
Whole Cake Island      732.000000
Zou                    750.000000
Name: Episode, dtype: float64

In [15]:
#Multiple Aggregations Together
import pandas as pd
df = pd.read_csv("one_piece.csv")

df.groupby("Arc")["Episode"].agg(["count", "mean", "max"])

                     count        mean  max
Arc
Alabasta                 3   78.000000   91
Amazon Lily              1  410.000000  410
Baratie                  2   21.500000   23
Dressrosa                2  407.000000  663
Drum Island              1   81.000000   81
East Blue                5    3.400000    9
Fish-Man Island          1  430.000000  430
Impel Down               4  432.000000  440
Jaya                     1   96.000000   96
Loguetown                3   49.333333   52
Long Ring Long Land      1  227.000000  227
Marineford               5  176.400000  278
Orange Town              1    4.000000    4
Sabaody                  3  396.000000  398
Skypiea                  1  167.000000  167
Thriller Bark            4  293.500000  343
Wano                     3  858.333333  918
Water 7                  5  197.600000  233
Whole Cake Island        3  732.000000  825
Zou                      1  750.000000  750

In [16]:
#Aggregation on Multiple Columns

import pandas as pd
df = pd.read_csv("one_piece.csv")

df.groupby("Arc").agg({
    "Episode": ["mean", "max"],
    "Name": "count"
})

                        Episode       Name
                           mean  max count
Arc
Alabasta              78.000000   91     3
Amazon Lily          410.000000  410     1
Baratie               21.500000   23     2
Dressrosa            407.000000  663     2
Drum Island           81.000000   81     1
East Blue              3.400000    9     5
Fish-Man Island      430.000000  430     1
Impel Down           432.000000  440     4
Jaya                  96.000000   96     1
Loguetown             49.333333   52     3
Long Ring Long Land  227.000000  227     1
Marineford           176.400000  278     5
Orange Town            4.000000    4     1
Sabaody              396.000000  398     3
Skypiea              167.000000  167     1
Thriller Bark        293.500000  343     4
Wano                 858.333333  918     3
Water 7              197.600000  233     5
Whole Cake Island    732.000000  825     3
Zou                  750.000000  750     1

In [17]:
#Reset Index (Cleaner Output)
import pandas as pd
df = pd.read_csv("one_piece.csv")

result = df.groupby("Arc")["Name"].count().reset_index()
print(result)

                    Arc  Name
0              Alabasta     3
1           Amazon Lily     1
2               Baratie     2
3             Dressrosa     2
4           Drum Island     1
5             East Blue     5
6       Fish-Man Island     1
7            Impel Down     4
8                  Jaya     1
9             Loguetown     3
10  Long Ring Long Land     1
11           Marineford     5
12          Orange Town     1
13              Sabaody     3
14              Skypiea     1
15        Thriller Bark     4
16                 Wano     3
17              Water 7     5
18    Whole Cake Island     3
19                  Zou     1

**DATA CLEANING** it’s all about fixing messy, incorrect, or incomplete data so your analysis becomes accurate.

In [18]:
#Check Your Data First

import pandas as pd
df = pd.read_csv("one_piece.csv")

print(df.head())      # first few rows
print(df.info())      # structure + data types
print(df.isnull().sum())  # missing values

   ID             Name       Role  Episode        Arc
0   1  Monkey D. Luffy    Captain        1  East Blue
1   2     Roronoa Zoro  Swordsman        2  East Blue
2   3             Nami  Navigator        1  East Blue
3   4            Usopp     Sniper        9  East Blue
4   5            Sanji       Cook       20    Baratie
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       50 non-null     int64
 1   Name     50 non-null     object
 2   Role     50 non-null     object
 3   Episode  50 non-null     int64
 4   Arc      50 non-null     object
dtypes: int64(2), object(3)
memory usage: 2.1+ KB
None
ID         0
Name       0
Role       0
Episode    0
Arc        0
dtype: int64

In [20]:
import pandas as pd
df = pd.read_csv("one_piece.csv")

df = df.dropna()

In [21]:
import pandas as pd
df = pd.read_csv("one_piece.csv")

df["Arc"] = df["Arc"].fillna("Unknown")
df["Episode"] = df["Episode"].fillna(0)

In [22]:
import pandas as pd
df = pd.read_csv("one_piece.csv")

df = df.drop_duplicates(subset="Name")

In [27]:
#Fix Column Names
import pandas as pd
df = pd.read_csv("one_piece.csv")

df.columns = df.columns.str.strip().str.lower()

In [23]:
#Fix Text Data - Removes spaces & standardizes format
import pandas as pd
df = pd.read_csv("one_piece.csv")

df["Name"] = df["Name"].str.strip()
df["Arc"] = df["Arc"].str.title()

In [24]:
#Convert Data Types- Sometimes numbers are read as strings → fix them
import pandas as pd
df = pd.read_csv("one_piece.csv")

df["Episode"] = df["Episode"].astype(int)

In [25]:
#Rename Columns
import pandas as pd
df = pd.read_csv("one_piece.csv")

df.rename(columns={"Episode": "episode_no"}, inplace=True)

In [26]:
#Replace Wrong Values
import pandas as pd
df = pd.read_csv("one_piece.csv")

df["Arc"] = df["Arc"].replace("wano", "Wano")